spring.application.name=bandas
spring.datasource.url=jdbc:postgresql://localhost:5433/bandas
spring.datasource.username=admin
spring.datasource.password=12345

#spring.datasource.url=jdbc:postgresql://pg-principios-project-09c2.g.aivencloud.com:15633/bandasdb
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_0t3ibXzl_XhmwzVuG_8

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

pablo.app.jwtSecret=pabloSecretKeyBands2026_MuyLargaParaSeguridad
pablo.app.jwtExpirationMs=86400000