spring.application.name=campusvirtual

spring.datasource.url=jdbc:postgresql://pg-principios-project-09c2.g.aivencloud.com:15633/bandasdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_0t3ibXzl_XhmwzVuG_8

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
server.forward-headers-strategy=native

