spring.application.name=demopg


spring.datasource.url=jdbc:postgresql://localhost:5433/spring
spring.datasource.username=admin
spring.datasource.password=12345

#spring.datasource.url=jdbc:postgresql://pg-principios-project-09c2.g.aivencloud.com:15633/defaultdb
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_0t3ibXzl_XhmwzVuG_8


spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

bezkoder.app.jwtSecret=bW9ja3NlY3JldC1rZXktZm9yLWRlbW8tcHVycG9zZXMtb25seS0zMmJ5dGVzLWxvbmc=
bezkoder.app.jwtExpirationMs=604800000
